### ISSUE TITLE
Info display windows no longer appear after Sagat update.

### ISSUE THREAD

**Issue by mintcheetos** [WistfulHopes/SF6Mods#20]
Can't get the ranges window to show up after the most recent update 

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/71ee58fb-4101-4b43-bb0f-834229f907c2" />

**Comment by Spabobin** [comment]
It works for me still, try with the newest [nightly REF](https://github.com/praydog/REFramework-nightly/releases)

EDIT: forgot I had been using a different branch version of infodisplay, the update that was just pushed should fix it

**Comment by mintcheetos** [comment]
still no luck for me. It saved my rebinds from previous build, is there a way to reset reframework to the default settings, for peace of mind? also getting this error 

<img width="629" height="83" alt="Image" src="https://github.com/user-attachments/assets/ceb3e44b-9848-4001-8faf-567c884819c6" />

**Comment by Cnul971** [comment]
<img width="2560" height="1600" alt="Image" src="https://github.com/user-attachments/assets/3046f47a-a6ff-4642-b310-f7f6bad855cb" />
I have the exact same error but since Elena update for me (no info display and the same error message)
